# Generated by Django 5.0.7 on 2024-08-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.CharField(blank=True, max_length=200, null=True)),
                ('end_time', models.CharField(blank=True, max_length=200, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'event_booking',
            },
        ),
    ]
