# Generated by Django 5.0.7 on 2024-07-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_booking',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event_booking',
            name='numberofpersons',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event_booking',
            name='reservationdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
